
model: "MACE"
num_channels: 32
max_L: 0
r_max: 5.0
E0s: "average"
name: "mace02_com1"
model_dir: "MACE_models"
log_dir: "MACE_models"
checkpoints_dir: "MACE_models"
results_dir: "MACE_models"
train_file: "../data/zr-w-v-cr-ti/mace_fep_train.xyz"
valid_file: "../data/zr-w-v-cr-ti/mace_fep_val.xyz"
test_file: "../data/zr-w-v-cr-ti/mace_fep_test.xyz"
energy_key: "REF_energy"
forces_key: "REF_force"
stress_key: "REF_stress"
loss: "stress"
energy_weight: 1.0
forces_weight: 50.0
stress_weight: 25.0
lr: 0.001
default_dtype: "float32"
device: mps
batch_size: 5
max_num_epochs: 200
swa: True
seed: 123
