model: "MACE"
num_channels: 32
max_L: 0
r_max: 4.0
lr: 0.001
name: "mace_gen_0_model_01"
model_dir: "MACE_models"
log_dir: "MACE_models"
checkpoints_dir: "MACE_models"
E0s: "average"
results_dir: "MACE_models"
train_file: "../data/w-14_train.xyz"
valid_file: "../data/w-14_valid.xyz"
test_file: "../data/w-14_test.xyz"
energy_key: "REF_energy"
forces_key: "REF_force"
device: cuda
batch_size: 64
max_num_epochs: 50
swa: True
seed: 0